from langchain_chroma import Chroma
from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings

from .schemas import EmbeddedChunk


class DocumentVectorStore:
    """
    Vector store for pre-computed document embeddings.

    Responsibilities:
    - Store document embeddings.
    - Preserve document text and metadata.
    - Perform similarity search.
    - Provide a retriever for RAG.
    """

    def __init__(
        self,
        persist_directory: str = "vector_db",
        collection_name: str = "documents",
        embedding_model: str = "sentence-transformers/all-mpnet-base-v2",
    ):
        # Used only for embedding user queries during retrieval.
        # Document embeddings are already generated by DocumentEmbedder.
        self.embeddings = HuggingFaceEmbeddings(
            model_name=embedding_model,
            encode_kwargs={
                "normalize_embeddings": True,
            },
        )

        self.vector_store = Chroma(
            collection_name=collection_name,
            persist_directory=persist_directory,
            embedding_function=self.embeddings,
        )
    def add_embeddings(
        self,
        embedded_chunks: list[EmbeddedChunk],
    ) -> None:
        """
        Store pre-computed embeddings in Chroma.
        """

        if not embedded_chunks:
            return

        ids = [
            str(i)
            for i in range(len(embedded_chunks))
        ]

        documents = [
            chunk.text
            for chunk in embedded_chunks
        ]

        embeddings = [
            chunk.embedding
            for chunk in embedded_chunks
        ]

        metadatas = [
            chunk.metadata
            for chunk in embedded_chunks
        ]

        self.vector_store._collection.add(
            ids=ids,
            documents=documents,
            embeddings=embeddings,
            metadatas=metadatas,
        )

    def similarity_search(
        self,
        query: str,
        k: int = 4,
    ) -> list[Document]:
        """
        Retrieve the most relevant documents for a query.
        """

        return self.vector_store.similarity_search(
            query,
            k=k,
        )

    def get_retriever(self, k: int = 4):
        """
        Return a retriever compatible with Naive RAG
        and Agentic RAG.
        """

        return self.vector_store.as_retriever(
            search_kwargs={
                "k": k,
            }
        )

    def count(self) -> int:
        """
        Return the number of stored document chunks.
        """

        return self.vector_store._collection.count()